name: Crash Report
description: Create a crash report
title: "[Crash Report]: "
assignees:
  - TheButterbrotMan
labels: ["Crash"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What Happened?
      description: Please provide a detailed description of the issue you encountered.
      placeholder: "When submitting the form without entering any data, the form validation error message does not appear. The form should display an error message prompting the user to fill in the required fields.

Steps to Reproduce:
1. Open the form.
2. Leave all the fields blank.
3. Click on the "Submit" button."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you currently using?
      placeholder: "1.0.0"
    validations:
      required: true
  
  - type: textarea
    id: latest_log
    attributes:
      label: Latest Log
      description: "Please paste the latest log below, between backticks."
      placeholder: "``"
    validations:
      required: true
