name: Bug Report
description: Create a bug report
title: "[Bug Report]: "
assignees:
  - TheButterbrotMan
labels: ["Bug"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What Happened?
      description: Please provide a detailed description of the issue you encountered.
      placeholder: Describe the problem you encountered.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you currently using?
      placeholder: Enter the version number.
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Log Files
      description: "If available, please upload the log files to [Crashy](https://crashy.net/) and provide the link here."
      placeholder: Enter the link to the log files.
