name: Crash Report
description: Create a crash report
title: "[Crash Report]: "
assignees:
  - TheButterbrotMan
labels: ["Crash"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What Happened?
      description: Please provide a detailed description of the issue you encountered.
      placeholder: "When attempting to submit the form, the application crashes consistently, displaying a 'Fatal Error' message. This occurs regardless of the entered data or any specific actions taken prior to clicking the 'Submit' button."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you currently using?
      placeholder: "2.1.0"
    validations:
      required: true

  - type: input
    id: log
    attributes:
      label: Crash Log File
      description: "If available, please upload the crash log file to [Crashy](https://crashy.net/) and provide the link here."
      placeholder: "https://crashy.net/db016a7f-90bd-4023-8e79-e66c9285cb2f"
