name: Bug Report
description: Create a report to help us improve
title: '[Bug]: '
assignees:
  - TheButterbrotMan
labels: ["Bug"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Please describe the issue you encountered in detail.
      placeholder: Explain the problem you encountered.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      placeholder: Enter the version number.
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Log files
      description: If available, provide any relevant log files.
      placeholder: You can upload log files (e.g. Bytebin) and provide the link here.
