name: Feature Request
description: Create a feature request
title: '[Feature Request]: '
assignees:
  - TheButterbrotMan
labels: ["Feature"]
body:
  - type: textarea
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe it.
      placeholder: I'm always frustrated when [...]
  - type: textarea
    attributes:
      label: Desired Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
